const PLAY_CARD_STATES = Object.freeze({
    NOT_ENOUGH_DON: 'NOT_ENOUGH_DON',
    CHARACTER_PLAYED: 'CARD_PLAYED',
    CHARACER_REPLACED_AND_PLAYED: 'CARD_PLAYED_AND_REPLACE',
    STAGE_PLAYED: 'STAGE_PLAYED',
    STAGE_REPLACED_AND_PLAYED: 'STAGE_PLAYED_AND_REPLACE',
    SELECT_REPLACEMENT_TARGET: 'SELECT_REPLACEMENT_TARGET',
});

const CARD_TYPES = Object.freeze({
    CHARACTER: 'CHARACTER',
    STAGE: 'STAGE',
    LEADER: 'LEADER',
    EVENT: 'EVENT',
});

module.exports = {
    PLAY_CARD_STATES: PLAY_CARD_STATES,
    CARD_TYPES: CARD_TYPES,
};