const PLAY_CARD_STATES = Object.freeze({
    NOT_ENOUGH_DON: 'NOT_ENOUGH_DON',
    CARD_BEING_PLAYED: 'CARD_BEING_PLAYED',
    CARD_PLAYED: 'CARD_PLAYED',
    CARD_REPLACED_AND_PLAYED: 'CARD_REPLACED_AND_PLAYED',
    NO_REPLACEMENT: 'NO_REPLACEMENT',
    SELECT_REPLACEMENT_TARGET: 'SELECT_REPLACEMENT_TARGET',
    ON_PLAY_EVENT_TARGETS_REQUIRED: 'ON_PLAY_EVENT_TARGETS_REQUIRED',
    EVENT_TARGETS_REQUIRED: 'EVENT_TARGETS_REQUIRED',
    EVENT_RESOLVED: 'EVENT_RESOLVED',
    NO_ON_PLAY_EVENT: 'NO_ON_PLAY_EVENT',
    ON_ATTACK_EVENT_TARGETS_REQUIRED: 'ON_ATTACK_EVENT_TARGETS_REQUIRED',
    TRIGGER_EVENT_TARGETS_REQUIRED: 'TRIGGER_EVENT_TARGETS_REQUIRED',
    ABILITY_TARGETS_REQUIRED: 'ABILITY_TARGETS_REQUIRED',
    CONDITIONS_NOT_MET: 'CONDITIONS_NOT_MET',
});

const ATTACK_CARD_STATES = Object.freeze({
    SELECT_TARGET: 'SELECT_ATTACK_TARGET',
});

const ATTACH_DON_TO_CHAR_STATES = Object.freeze({
    DON_NOT_READY: 'DON_NOT_READY',
    DON_ATTACHED: 'DON_ATTACHED',
});

const CARD_TYPES = Object.freeze({
    CHARACTER: 'CHARACTER',
    STAGE: 'STAGE',
    LEADER: 'LEADER',
    EVENT: 'EVENT',
});

const MATCH_CONSTANTS = Object.freeze({
    MAX_CHARACTERS_IN_AREA: 5,
});

const TARGET_ACTION = Object.freeze({
    PLAY_CARD_REPLACE_ACTION: 'PLAY_CARD_REPLACE_ACTION',
    ATTACK_CARD_ACTION: 'ATTACK_CARD_ACTION',
    ABILITY_ACTION: 'ABILITY_ACTION',
});

module.exports = {
    PLAY_CARD_STATES: PLAY_CARD_STATES,
    ATTACK_CARD_STATES: ATTACK_CARD_STATES,
    CARD_TYPES: CARD_TYPES,
    ATTACH_DON_TO_CHAR_STATES: ATTACH_DON_TO_CHAR_STATES,
    MATCH_CONSTANTS: MATCH_CONSTANTS,
    TARGET_ACTION: TARGET_ACTION,
};