const GAME_UI_CONSTANTS = Object.freeze({
    COMPONENT_SEPARATOR_WIDTH: 20,
    COMPONENT_SEPARATOR_HEIGHT: 20,

    CARD_ART_WIDTH: 600,
    CARD_ART_HEIGHT: 838,

    HAND_CARD_SEPARATION: 0.5
});

const PLAYER_POSITIONS = Object.freeze({
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',
});

const CARD_STATES = Object.freeze({
    IN_DECK: 'IN_DECK',
    IN_HAND: 'IN_HAND',
    IN_HAND_HOVERED: 'IN_HAND_HOVERED',
    IN_DISCARD: 'IN_DISCARD',
    IN_LOCATION: 'IN_LOCATION',

    TRAVELLING_DECK_HAND: 'TRAVELLING_DECK_HAND',
    TRAVELLING_FROM_HAND: 'TRAVELLING_FROM_HAND',
});

const CARD_TYPES = Object.freeze({
    CHARACTER: 'CHARACTER',
    EVENT: 'EVENT',
    STAGE: 'STAGE',
    LEADER: 'LEADER',
    DON: 'DON',
});

const CARD_SCALE = Object.freeze({
    IN_DON_DECK: 0.11,
    IN_DECK: 0.13,
    IN_HAND: 0.27,
    IN_HAND_HOVERED: 0.45,

    TRAVELLING_FROM_HAND:0.2,

    IN_DISCARD: 0.11,
    IN_LOCATION: 0.18,
    IN_PLAY_ANIMATION: 0.25,

    IN_LOCATION_LEADER: 0.23 
});

const GAME_PHASES = Object.freeze({
    SETUP: 'Setup',
    DON_PHASE: 'Don Phase',
});