const GAME_UI_CONSTANTS = Object.freeze({
    COMPONENT_SEPARATOR_WIDTH: 20,
    COMPONENT_SEPARATOR_HEIGHT: 20,

    CARD_ART_WIDTH: 600,
    CARD_ART_HEIGHT: 838,

    HAND_CARD_SEPARATION: 0.5
});

const PLAYER_POSITIONS = Object.freeze({
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',
});

const CARD_STATES = Object.freeze({
    IN_DECK: 'IN_DECK',
    IN_HAND: 'IN_HAND',
    IN_HAND_HOVERED: 'IN_HAND_HOVERED',

    IN_HAND_PASSIVE_PLAYER: 'IN_HAND_PASSIVE_PLAYER',
    IN_HAND_HOVERED_PASSIVEPLAYER: 'IN_HAND_HOVERED_PASSIVEPLAYER',

    IN_DISCARD: 'IN_DISCARD',
    IN_MULLIGAN: 'IN_MULLIGAN',
    IN_LIFEDECK: 'IN_LIFEDECK',

    IN_PLAY: 'IN_PLAY',
    IN_PLAY_RESTED: 'IN_PLAY_RESTED',
    IN_PLAY_FIRST_TURN: 'IN_PLAY_FIRST_TURN',
    IN_PLAY_ATTACHED: 'IN_PLAY_ATTACHED',
    IN_PLAY_ATTACKING: 'IN_PLAY_ATTACKING',
    IN_PLAY_DEFENDING: 'IN_PLAY_DEFENDING',
    IN_PLAY_TARGETTING: 'IN_PLAY_TARGETTING',
    
    IN_PLAY_TARGETTING: 'IN_PLAY_TARGETTING',
    
    LEADER_TRAVELLING_TO_LOCATION: 'LEADER_TRAVELLING_TO_LOCATION',

    TRAVELLING_TO_HAND: 'TRAVELLING_TO_HAND',
    TRAVELLING_FROM_HAND: 'TRAVELLING_FROM_HAND',
    TRAVELLING_DURING_COUNTER: 'TRAVELLING_DURING_COUNTER',
    TRAVELLING_TO_DECK: 'TRAVELLING_TO_DECK',

    IN_DON_DECK: 'IN_DON_DECK',
    DON_ACTIVE: 'DON_ACTIVE',
    DON_RESTED: 'DON_RESTED',
    DON_ATTACHED: 'DON_ATTACHED',
    DON_TRAVELLING: 'DON_TRAVELLING',
});

const CARD_TYPES = Object.freeze({
    CHARACTER: 'CHARACTER',
    EVENT: 'EVENT',
    STAGE: 'STAGE',
    LEADER: 'LEADER',
    DON: 'DON',
});

const CARD_SCALE = Object.freeze({
    IN_DON_DECK: 0.11,
    IN_DECK: 0.13,
    IN_HAND: 0.25,
    IN_HAND_HOVERED: 0.4,
    IN_MULLIGAN: 0.4,

    TRAVELLING_FROM_HAND:0.2,

    IN_DISCARD: 0.11,
    IN_LOCATION: 0.18,
    IN_PLAY_ANIMATION: 0.3,

    COUNTER_OVER_CARD: 0.1,

    IN_LOCATION_LEADER: 0.23, 

    IN_HAND_PASSIVE_PLAYER: 0.18,
    IN_HAND_HOVERED_PASSIVE_PLAYER: 0.22,
    IN_MULLIGAN_PASSIVE_PLAYER: 0.15,

    DON_IN_DON_DECK: 0.11,
    DON_IN_ACTIVE_DON: 0.09,
    DON_OVER_CHARACTER: 0.05,
    
});

const DEPTH_VALUES = Object.freeze({
    DON_IN_PILE: 1,
    DON_DRAGGED: 2,

    CARD_IN_DECK: 1,
    CARD_IN_HAND: 2,
    CARD_IN_PLAY: 1,
    CARD_IN_MULLIGAN: 5,
    CARD_IN_MULLIGAN_PASSIVE_PLAYER: 2,
    CARD_ATTACKING_ANIMATION: 6,
    CARD_DEFENDING_ANIMATION: 5,
});

const GAME_PHASES = Object.freeze({
    SETUP: 'Setup',
    MULLIGAN_PHASE: 'Mulligan Phase',
    PREPARING_FIRST_TURN: 'Setup Phase',
    REFRESH_PHASE: 'Refresh Phase',
    DRAW_PHASE: 'Draw Phase',
    DON_PHASE: 'Don Phase',
    MAIN_PHASE: 'Main Phase',
    ATTACK_PHASE: 'Main: Attack',
    BLOCK_PHASE: 'Main: Block',
    COUNTER_PHASE: 'Main: Counter',
});