const GAME_UI_CONSTANTS = Object.freeze({
    COMPONENT_SEPARATOR_WIDTH: 20,
    COMPONENT_SEPARATOR_HEIGHT: 20,

    CARD_ART_WIDTH: 600,
    CARD_ART_HEIGHT: 838,

    HAND_CARD_SEPARATION: 0.5
});

const PLAYER_POSITIONS = Object.freeze({
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',
});

const CARD_STATES = Object.freeze({
    IN_DECK: 'IN_DECK',
    IN_HAND: 'IN_HAND',
    IN_HAND_HOVERED: 'IN_HAND_HOVERED',
    IN_HAND_HOVERED_PASSIVEPLAYER: 'IN_HAND_HOVERED_PASSIVEPLAYER',
    IN_DISCARD: 'IN_DISCARD',
    IN_LOCATION: 'IN_LOCATION',
    IN_MULLIGAN: 'IN_MULLIGAN',
    IN_LIFEDECK: 'IN_LIFEDECK',
    
    LEADER_TRAVELLING_TO_LOCATION: 'LEADER_TRAVELLING_TO_LOCATION',

    TRAVELLING_DECK_HAND: 'TRAVELLING_DECK_HAND',
    TRAVELLING_FROM_HAND: 'TRAVELLING_FROM_HAND',

    IN_DON_DECK: 'IN_DON_DECK',
    DON_ACTIVE: 'DON_ACTIVE',
    DON_EXERTED: 'DON_EXERTED',
    DON_ATTACHED: 'DON_ATTACHED',
    DON_DRAGGED: 'DON_DRAGGED',
});

const CARD_TYPES = Object.freeze({
    CHARACTER: 'CHARACTER',
    EVENT: 'EVENT',
    STAGE: 'STAGE',
    LEADER: 'LEADER',
    DON: 'DON',
});

const CARD_SCALE = Object.freeze({
    IN_DON_DECK: 0.11,
    IN_DECK: 0.13,
    IN_HAND: 0.25,
    IN_HAND_HOVERED: 0.4,
    IN_MULLIGAN: 0.4,

    TRAVELLING_FROM_HAND:0.2,

    IN_DISCARD: 0.11,
    IN_LOCATION: 0.18,
    IN_PLAY_ANIMATION: 0.25,

    IN_LOCATION_LEADER: 0.23, 

    IN_HAND_PASSIVE_PLAYER: 0.18,
    IN_HAND_HOVERED_PASSIVE_PLAYER: 0.22,
    IN_MULLIGAN_PASSIVE_PLAYER: 0.15,

    DON_IN_DON_DECK: 0.11,
    DON_IN_ACTIVE_DON: 0.09,
    
});

const GAME_PHASES = Object.freeze({
    SETUP: 'Setup',
    MULLIGAN_PHASE: 'Mulligan Phase',
    PREPARING_FIRST_TURN: 'Setup Phase',
    REFRESH_PHASE: 'Refresh Phase',
    DRAW_PHASE: 'Draw Phase',
    DON_PHASE: 'Don Phase',
    MAIN_PHASE: 'Main Phase',
});